-  Hi, I’m @Eneyoki
-  I’m interested in collaborating with data analyst...
-  I’m currently learning data analytics ...
-  I’m looking to collaborate on  data cleaning and data analytics...
-  How to reach me maisondeeneyoki@gmail.com...
-  Pronouns: her...
-  Fun fact: i love traveling and i speak english and french...

<!---
Eneyoki/Eneyoki is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
